### ISSUE TITLE
at.stefl.commons.io.ByteStreamUtil.readFully(ByteStreamUtil.java:97)

### ISSUE THREAD

**Issue by foobnix** [andiwand/OpenDocument.java#20]
java.io.EOFException
[file-sample_100kB.odt.zip](https://github.com/andiwand/OpenDocument.java/files/2644548/file-sample_100kB.odt.zip)

12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.commons.io.ByteStreamUtil.readFully(ByteStreamUtil.java:97)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.commons.io.ByteDataInputStream.readUnit(ByteDataInputStream.java:61)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.commons.io.ByteDataInputStream.readInt(ByteDataInputStream.java:95)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.io.SVMDataInputStream.readVector2i(SVMDataInputStream.java:39)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.io.SVMDataInputStream.readSize(SVMDataInputStream.java:84)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.object.SVMHeader.deserializeContent(SVMHeader.java:107)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.object.SVMVersionObject.deserialize(SVMVersionObject.java:38)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.object.SVMHeader.deserialize(SVMHeader.java:82)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.io.SVMReader.readHeader(SVMReader.java:32)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.svm.tosvg.SVGTranslator.translate(SVGTranslator.java:71)
12-04 15:00:05.594  1767  2311 E DEBUG   : 	at at.stefl.opendocument.java.translator.image.SVM2SVGConverter.convert(SVM2SVGConverter.java:28)

**Comment by andiwand** [comment]
if you can provide a fix i would merge it.
