### ISSUE TITLE
Some odp-files cause EOFException

### ISSUE THREAD

**Issue by TomTasche** [andiwand/OpenDocument.java#23]
> 2019-01-20 13:43:20.771 23658-23658/at.tomtasche.reader E/OpenDocument Reader: Error opening file at content://com.google.android.apps.docs.storage/document/acc%3D1%3Bdoc%3D3513
>     java.io.EOFException
>         at at.stefl.commons.io.ByteStreamUtil.readFully(ByteStreamUtil.java:97)
>         at at.stefl.commons.io.ByteDataInputStream.readUnit(ByteDataInputStream.java:61)
>         at at.stefl.commons.io.ByteDataInputStream.readInt(ByteDataInputStream.java:95)
>         at at.stefl.svm.io.SVMDataInputStream.readVector2i(SVMDataInputStream.java:39)
>         at at.stefl.svm.io.SVMDataInputStream.readSize(SVMDataInputStream.java:84)
>         at at.stefl.svm.object.SVMHeader.deserializeContent(SVMHeader.java:107)
>         at at.stefl.svm.object.SVMVersionObject.deserialize(SVMVersionObject.java:38)
>         at at.stefl.svm.object.SVMHeader.deserialize(SVMHeader.java:82)
>         at at.stefl.svm.io.SVMReader.readHeader(SVMReader.java:32)
>         at at.stefl.svm.tosvg.SVGTranslator.translate(SVGTranslator.java:71)
>         at at.stefl.opendocument.java.translator.image.SVM2SVGConverter.convert(SVM2SVGConverter.java:28)
>         at at.stefl.opendocument.java.translator.content.ImageTranslator.writeSource(ImageTranslator.java:131)
>         at at.stefl.opendocument.java.translator.content.ImageTranslator.translateAttributeList(ImageTranslator.java:80)
>         at at.stefl.opendocument.java.translator.content.ImageTranslator.translateAttributeList(ImageTranslator.java:1)
>         at at.stefl.commons.lwxml.translator.LWXMLDefaultElementTranslator.translate(LWXMLDefaultElementTranslator.java:98)
>         at at.stefl.commons.lwxml.translator.LWXMLDefaultElementTranslator.translate(LWXMLDefaultElementTranslator.java:1)
>         at at.stefl.commons.lwxml.translator.LWXMLHierarchyTranslator.translate(LWXMLHierarchyTranslator.java:79)
>         at at.stefl.opendocument.java.translator.document.GenericBulkDocumentTranslator.translateContent(GenericBulkDocumentTranslator.java:63)
>         at at.stefl.opendocument.java.translator.document.GenericDocumentTranslator.translateGeneric(GenericDocumentTranslator.java:130)
>         at at.stefl.opendocument.java.translator.document.GenericDocumentTranslator.translate(GenericDocumentTranslator.java:108)
>         at at.stefl.opendocument.java.translator.document.GenericBulkDocumentTranslator.translate(GenericBulkDocumentTranslator.java:47)
>         at at.tomtasche.reader.background.DocumentLoader.loadSync(DocumentLoader.java:196)
> 

Files downloaded from here: http://file-examples.com/index.php/sample-documents-download/sample-odp-download/
[file_example_ODP_.zip](https://github.com/andiwand/OpenDocument.java/files/2776584/file_example_ODP_.zip)

**Comment by andiwand** [comment]
seems to be a problem of https://github.com/andiwand/svm

**Comment by TomTasche** [comment]
Same for specific ODT-files. I can share them with you privately if necessary (sent by customer).

**Comment by TomTasche** [comment]
According to our analytics this happens quite often (400 times in the last 7 days)

**Comment by TomTasche** [comment]
Duplicate of https://github.com/andiwand/OpenDocument.java/issues/20
